# kubernetes/base/postgres-cluster.yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: odoo-postgres-cluster
  labels:
    app: odoo-postgres
spec:
  teamId: "odoo"
  volume:
    size: 100Gi
    storageClass: fast-ssd
  numberOfInstances: 3
  
  users:
    odoo:  # application user
    - superuser
    - createdb
  
  databases:
    odoo_prod: odoo
    odoo_stage: odoo
    odoo_dev: odoo
  
  postgresql:
    version: "15"
    parameters:
      # Performance
      max_connections: "300"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "10485kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
      
      # Logging
      log_min_duration_statement: "1000"
      log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
      log_temp_files: "0"
      
      # Replication
      wal_level: "replica"
      hot_standby: "on"
      max_wal_senders: "10"
      max_replication_slots: "10"
      hot_standby_feedback: "on"
      
      # Autovacuum
      autovacuum_max_workers: "3"
      autovacuum_naptime: "60s"
      
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"
  
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "uk_UA.UTF-8"
      data-checksums: "true"
    pg_hba:
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 33554432
    
    synchronous_mode: true
    synchronous_mode_strict: false
    
  # Backup configuration
  enableShmVolume: true
  enableConnectionPooler: true  # PgBouncer
  enableReplicaConnectionPooler: true
  
  # Connection pooler (PgBouncer)
  connectionPooler:
    numberOfInstances: 2
    mode: "transaction"
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
  # Monitoring
  enableLogicalBackup: true
  logicalBackupSchedule: "30 00 * * *"
  
  sidecars:
    - name: exporter
      image: prometheuscommunity/postgres-exporter:latest
      ports:
        - containerPort: 9187
          name: metrics
      env:
        - name: DATA_SOURCE_URI
          value: "localhost:5432/postgres?sslmode=disable"
        - name: DATA_SOURCE_USER
          value: "postgres"
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.odoo-postgres-cluster.credentials.postgresql.acid.zalan.do
              key: password
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"